apiVersion: apps/v1

kind: Deployment

metadata:
  name: go-hpa

spec:
  replicas: 6

  selector:
    matchLabels:
      app: go-hpa

  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: zenatureza/go-hpa

          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
