apiVersion: autoscaling/v1

kind: horizontalPodAutoscaler

metadata:
  name: go-hpa

spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15
